version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dktc_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dktc_db
    ports:
      - "3309:3306"
    volumes:
      - dktc_db_data:/var/lib/mysql

volumes:
  dktc_db_data: